name: Notificação Discord

on:
  push:
    branches: [ "main" ]

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensagem para o Discord
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          ACTOR: ${{ github.actor }}
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          PAYLOAD=$(jq -n --arg content "🚀 Novo commit enviado para a main por $ACTOR: $COMMIT_MSG" '{content: $content}')
          curl -H "Content-Type: application/json" -X POST -d "$PAYLOAD" "$WEBHOOK"